### ISSUE TITLE
无法正常加载插件

### ISSUE THREAD

**Issue by Shrimpchu** [050644zf/nonebot-plugin-bfchat#14]
不论是nonebot商店测试结果还是我个人尝试加载都出现了如下错误：
  05-07 08:56:09 [ERROR] nonebot | Failed to import "nonebot_plugin_bfchat"
    Traceback (most recent call last):
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/runner.py", line 16, in <module>
        plugin = load_plugin("nonebot_plugin_bfchat")
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot/plugin/load.py", line 40, in load_plugin
        return manager.load_plugin(module_path)
    > File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
        module = importlib.import_module(self._third_party_plugin_ids[name])
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
        super().exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot_plugin_bfchat/__init__.py", line 15, in <module>
        from nonebot_plugin_htmlrender import md_to_pic, html_to_pic
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot_plugin_htmlrender/__init__.py", line 4, in <module>
        from .browser import get_browser, get_new_page, shutdown_browser
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/nonebot_plugin_htmlrender/browser.py", line 27, in <module>
        config = Config.parse_obj(get_driver().config.dict())
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/pydantic/main.py", line 1118, in parse_obj
        return cls.model_validate(obj)
      File "/home/runner/work/registry/registry/plugin_test/nonebot-plugin-bfchat-nonebot_plugin_bfchat-test/.venv/lib/python3.10/site-packages/pydantic/main.py", line 551, in model_validate
        return cls.__pydantic_validator__.validate_python(
    pydantic_core._pydantic_core.ValidationError: 3 validation errors for Config
    htmlrender_download_host
      Field required [type=missing, input_value={'driver': 'fake', 'host'....timedelta(seconds=120)}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.7/v/missing
    htmlrender_proxy_host
      Field required [type=missing, input_value={'driver': 'fake', 'host'....timedelta(seconds=120)}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.7/v/missing
    htmlrender_browser_channel
      Field required [type=missing, input_value={'driver': 'fake', 'host'....timedelta(seconds=120)}, input_type=dict]
        For further information visit https://errors.pydantic.dev/2.7/v/missing

**Comment by 050644zf** [comment]
疑似htmlrenderer插件的类型检查报错，但看了一下报错的都是它的可选配置项。我这边尝试重新安装插件也没能复现。

@kexue-z 能提供一点思路吗？

**Comment by 050644zf** [comment]
在v0.3.2尝试修复了htmlrenderer的导入方式，请再次尝试

**Comment by Shrimpchu** [comment]
仍然无法加载，报错如下：
`08-07 11:45:31 [ERROR] nonebot | Failed to import "nonebot_plugin_htmlrender"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot_plugin_bfchat\__init__.py", line 14, in <module>
    require("nonebot_plugin_htmlrender")
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 185, in require
    plugin = load_plugin(name)
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 40, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 4, in <module>
    from .browser import get_browser, get_new_page, shutdown_browser
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 27, in <module>
    config = Config.parse_obj(get_driver().config.dict())
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\pydantic\main.py", line 1135, in parse_obj
    return cls.model_validate(obj)
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\pydantic\main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Config
htmlrender_download_host
  Field required [type=missing, input_value={'driver': '~fastapi', 'h....timedelta(seconds=120)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
htmlrender_proxy_host
  Field required [type=missing, input_value={'driver': '~fastapi', 'h....timedelta(seconds=120)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
htmlrender_browser_channel
  Field required [type=missing, input_value={'driver': '~fastapi', 'h....timedelta(seconds=120)}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
08-07 11:45:31 [ERROR] nonebot | Failed to import "nonebot_plugin_bfchat"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot_plugin_bfchat\__init__.py", line 14, in <module>
    require("nonebot_plugin_htmlrender")
  File "C:\Users\Administrator\botKotone\.venv\Lib\site-packages\nonebot\plugin\load.py", line 188, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_htmlrender"!`

**Comment by 050644zf** [comment]
参考这个[issue](https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/43#issuecomment-1411402896)中有和你一样的报错。您是否也在使用低于3.10的python版本？

**Comment by Shrimpchu** [comment]
不，我确定我使用的是python 3.12

**Comment by 050644zf** [comment]
经过检查，发现问题由nonebot_plugin_htmlrender插件使用了pydantic v2版本，形成了较大改动导致。

现在推送`v0.4.0`版本，将依赖更新至最新版本，修复了导入问题。
