### ISSUE TITLE
在真寻bot中查询个人战绩出错

### ISSUE THREAD

**Issue by enldm** [050644zf/nonebot-plugin-bfchat#7]
服务器列表、帮助菜单可以正常返回，但是查询个人战绩出错，貌似是缺少图片？

03-31 08:45:08 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_bfchat.bfv) failed.
Traceback (most recent call last):
  File "bot.py", line 22, in <module>
    nonebot.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/drivers/fastapi.py", line 187, in run
    uvicorn.run(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/uvicorn/main.py", line 568, in run
    server.run()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot_plugin_bfchat/bfv.py", line 131, in bfv_handler
    html = apply_template(result,'bfv', PREFIX)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot_plugin_bfchat/template.py", line 153, in apply_template
    classes = get_classes_data(d, 5)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.8/lib/python3.8/site-packages/nonebot_plugin_bfchat/template.py", line 119, in get_classes_data
    s += CLASSES_CARD.format(c=c)
KeyError: 'avatarImages'

**Comment by enldm** [comment]
看了下log，，战地1和5同样错误 但是2042正常  bot位于ubuntu20.04的海外服务器上

**Comment by 050644zf** [comment]
确认bug，似乎是误调用了2042的专家模板，正在排查

**Comment by 050644zf** [comment]
在v0.3.1修复，现已发版，麻烦测试一下，如果没问题就close了，谢谢您的issue

**Comment by enldm** [comment]
谢谢修复 稍晚测试

From Android  Outlook<https://aka.ms/ghei36>
________________________________

**Comment by enldm** [comment]
> 在v0.3.1修复，现已发版，麻烦测试一下，如果没问题就close了，谢谢您的issue

已经可以正常用了。捉个小虫，如果在bot.py里加载的话应该注意是
nonebot.load_plugin("nonebot_plugin_bfchat")
而不是
nonebot.load_plugin("nonebot-plugin-bfchat")
